# Generated by Django 5.1.4 on 2025-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="task_asset"),
        ),
    ]
